#!/usr/bin/env bash

set -e
echo "Building binaries"
./build
echo "...Done"
cd dist

echo "Compressing binaries"
upx --lzma talisman_windows* talisman_linux* talisman_darwin_amd64
echo "...Done"

echo "Verifying compressed binaries"
upx -t talisman_windows* talisman_linux* talisman_darwin_amd64
echo "...Done"

echo "Generating checksums for download verification"
shasum -b -a256 talisman* >checksums
echo "...Done"

echo "Verifying checksums"
shasum -c checksums
echo "...Done"
