#!/bin/bash
set -e
VERSION=$(git describe --tags HEAD)
rm -rf dist/
mkdir -p dist/
gox -osarch="linux/amd64 linux/386 darwin/amd64 windows/amd64 windows/386" \
    -ldflags="-s -w -X main.Version=${VERSION}" \
    --output "dist/talisman_{{.OS}}_{{.Arch}}" \
    talisman/cmd
cd dist
upx --lzma talisman*
upx -t talisman*
shasum -b -a256 talisman* > checksums
