#!/bin/sh
set -e
echo "Building binaries"
./build
echo "...Done"
cd dist

echo "Compressing binaries"
upx --lzma talisman*
echo "...Done"

echo "Verifying compressed binaries"
upx -t talisman*
echo "...Done"

echo "Generating checksums for download verification"
shasum -b -a256 talisman* > checksums
echo "...Done"

echo "Verifying checksums"
shasum -c checksums
echo "...Done"
