codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: no
  status:
    project:
      default:
        target: 69%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch: off
  notify:
    after_n_builds: 2
    wait_for_ci: yes
    comment:
      layout: "reach, diff, flags, files"
      behavior: default
      require_changes: false  # if true: only post the comment if coverage changes
      require_base: no        # [yes :: must have a base report to post]
      require_head: yes       # [yes :: must have a head report to post]
      branches:               # branch names that can post comment
        - "master"
