package severity

var SeverityConfiguration = map[string]Severity{
	"ConsumerKeyPattern": High(),
	"ConsumerSecretParrern": High(),
	"AWSKeyPattern": High(),
	"AWSSecretPattern": High(),
	"RSAKeyPattern": High(),
	"DSAFile": High(),
	"PrivateKeyFile":High(),
	"CreditCardContent": High(),
	"PemFile": High(),
	"PpkFile": High(),
	"SecretToken": High(),
	"KeyPairFile": High(),
	"CustomPattern": High(),
	"PKCSFile": High(),
	"PFXFile": High(),
	"P12File": High(),
	"NetrcFile": High(),
	"RSAFile": High(),
	"KeyChainFile": High(),
	"KeyStoreFile": High(),
	"OauthTokenFile":High(),
	"HTPASSWDFile": High(),
	"TunnelBlockFile": High(),
	"CredentialsXML": High(),
	"JenkinsPublishOverSSHFile": High(),
	"PasswordPhrasePattern": Medium(),
	"OpenVPNFile": Medium(),
	"s3Config": Medium(),
	"LargeFileSize": Medium(),
	"Base64Content": Medium(),
	"HexContent": Medium(),
	"DatabaseYml": Medium(),
	"ShellHistory": Low(),
	"ASCFile": Low(),
	"KDBFile": Low(),
	"AgileKeyChainFile": Low(),
	"PubXML": Low(),
	"GitRobRC": Low(),
	"ShellRC": Low(),
	"ShellProfile": Low(),
	"ShellAlias": Low(),
	"OmniAuth": Low(),
	"CarrierWaveRB": Low(),
	"SchemaRB": Low(),
	"PythonSettings": Low(),
	"PhpConfig": Low(),
	"PhpLocalSettings": Low(),
	"EnvFile": Low(),
	"BDumpFile": Low(),
	"BSQLFile": Low(),
	"PasswordFile":Low(),
	"BackupFile":Low(),
	"LogFile":Low(),
	"KWallet":Low(),
	"GNUCash":Low(),
}